name: logger
description: "Logger that stores in D1 cloudflare database."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0-9.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloudflare_d1:
    git:
      url: https://github.com/yabzec/cloudflare_d1.git
      ref: main
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
